/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ir_mmd_linux_utility_font_n_FontConfig */

#ifndef _Included_ir_mmd_linux_utility_font_n_FontConfig
#define _Included_ir_mmd_linux_utility_font_n_FontConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ir_mmd_linux_utility_font_n_FontConfig
 * Method:    getAllFontPaths
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ir_mmd_linux_utility_font_n_FontConfig_getAllFontPaths
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
